# Generated by Django 3.2.4 on 2021-07-05 11:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profiles.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('mobile', models.CharField(blank=True, default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09123456789'. Only 11 digits allowed.", regex='^\\+?09?\\d{10}$')])),
                ('mobile_confirmed', models.BooleanField(default=False)),
                ('national_id', models.CharField(blank=True, default=None, max_length=10, null=True, validators=[profiles.validators.validate_national_ID])),
                ('national_id_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
